# Generated by Django 3.2.4 on 2021-06-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_alter_tour_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='num_of_spots_left',
            field=models.IntegerField(null=True),
        ),
    ]
