# Generated by Django 3.2.4 on 2021-06-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_tour_num_of_spots_left'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='num_of_spots_left',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
