# Generated by Django 3.2.4 on 2021-06-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_alter_tour_num_of_spots_left'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='ratings',
            field=models.FloatField(default=0),
        ),
    ]
